# actions-marketplace-validations/Zo-Bro-23_grs-action
name: GitHub Readme Stats
on:
  push:
    branches: main
  workflow_dispatch:
#   schedule:
#   - cron: 0 * * * *

jobs:
  grs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Generate Stats
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4
      - name: Generate Stats
        uses: actions-marketplace-validations/Zo-Bro-23_grs-action@main
        id: generate
        with:
          token: ${{ secrets.GH_TOKEN }}
          options: 'username=${{ github.repository_owner }}'
          path: 'grs/README.svg'
      - uses: actions/upload-artifact@master
        with:
          name: grs1
          path: grs