name: GitHub Readme Stats
on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *

jobs:
  grs:
    if: github.actor != 'sbxportfoliobot[bot]'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Generate Stats
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4
      - name: Generate Stats
        uses: BestJarvan/BestJarvan@master
        id: stats
        with:
          token: ${{ secrets.GH_TOKEN }}
          options: 'username=${{ github.repository_owner }}&hide=stars&show=prs_merged_percentage,prs_merged,reviews&show_icons=true&custom_title=My Stats (Public and Private)&theme=noctis_minimus'
          path: 'grs/stats.svg'
      - name: Generate Stats
        uses: BestJarvan/BestJarvan@master
        id: langs
        with:
          token: ${{ secrets.GH_TOKEN }}
          options: 'username=${{ github.repository_owner }}&custom_title=Most Used Languages (Public)&card_width=320&theme=noctis_minimus'
          card: 'top-langs'
          path: 'grs/langs.svg'
      - name: Push
        uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564 #v4
        with:
          target_branch: gh-stats
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
